# Generated by Django 5.2 on 2025-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraPagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.AddField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
