# Generated by Django 5.2 on 2025-04-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraPagina', '0002_remove_profesor_email_profesor_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
